apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-pre/pvc.yaml
#- 01-namespaces/cicd-environment.yaml
- 02-rolebindings/internal-registry-cicd-binding.yaml
- 02-rolebindings/pipeline-service-account.yaml
- 02-rolebindings/pipeline-service-role.yaml
- 02-rolebindings/pipeline-service-rolebinding.yaml
- 02-rolebindings/pipeline-privileged-rolebinding.yaml
#- 03-secrets/
- 04-tasks/task-deploy-from-source.yaml
- 04-tasks/task-maven.yaml
- 04-tasks/task-kaniko.yaml
- 04-tasks/task-buildah-privileged.yaml
- 04-tasks/task-buildah-tag-push.yaml
- 04-tasks/task-sonarqube-scanner.yaml
- 04-tasks/task-trivy.yaml
- 04-tasks/task-ibm-va.yaml
- 04-tasks/task-yq.yaml
- 04-tasks/task-promote-version.yaml
#- 05-pipelines/ci-pipeline-container.yaml
#- 05-pipelines/ci-pipeline-maven-kaniko.yaml
- 05-pipelines/ci-pipeline-maven-buildah.yaml
- 05-pipelines/ci-pipeline-promote.yaml
#- 05-pipelines/ci-dryrun-from-push-pipeline.yaml
- 05-pipelines/cd-pipeline-helm.yaml
- 06-bindings/binding-app-custom.yaml
- 06-bindings/binding-github-attributes.yaml
#- 07-templates/template-app-ci-build-from-push.yaml
#- 07-templates/template-ci-dryrun-from-push.yaml
- 07-templates/template-maven-ci-build-from-push.yaml
- 08-eventlisteners/cicd-event-listener.yaml
- 09-routes/gitops-webhook-event-listener.yaml
